# Generated by Django 6.0.6 on 2026-06-15 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_value', models.IntegerField()),
                ('work_environment', models.IntegerField()),
                ('career_growth', models.IntegerField()),
                ('salary_satisfaction', models.IntegerField()),
                ('job_security', models.IntegerField()),
                ('employee_respect', models.IntegerField(default=0)),
                ('fringe_benefits', models.IntegerField(default=0)),
                ('leadership_quality', models.IntegerField(default=0)),
                ('work_life_balance', models.IntegerField(default=0)),
                ('learning_opportunity', models.IntegerField(default=0)),
                ('recommendation', models.BooleanField(default=True)),
                ('anonymous', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_flagged', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
